# Generated by Django 2.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='trains',
            field=models.ManyToManyField(to='ldata.Train'),
        ),
    ]
